name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    #- name: List files in the repository
    #  run: |
    #    ls -aR ${{ github.workspace }}

    - name: Build release apk
      run: ./gradlew app:assembleFullRelease

    #- name: List files in the repository
    #  run: |
    #    ls -aR ${{ github.workspace }}

    - name: Setup build tool version variable
      shell: bash
      run: |
        BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
        echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
        echo Last build tool version is: $BUILD_TOOL_VERSION
        
    - name: Sign App
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/full/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: 'msarna'
        keyStorePassword: '123456'
        keyPassword: '123456'
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

    - name: Upload APK Release
      uses: actions/upload-artifact@v3
      with:
        name: APK release generated
        path: app/build/outputs/apk/full/release

    #- name: Releasing using Hub
    #  uses: sangatdesai/release-apk@main
    #  env:
    #   GITHUB_TOKEN: ${{ secrets.TOKEN }}
    #   APP_FOLDER: app
